### ISSUE TITLE
process exited with code 1

### ISSUE THREAD

**Issue by umer2001** [vaibhavpandeyvpz/apkstudio#100]
can you tell how to solve?
it occured while decompiling the app
$ java -Xmx128m -jar "C:/Users/farooq sharif/.apkstudio/vendor/apktool.jar" -f d "C:/Users/farooq sharif/Desktop/mod/Green DOT Cash_androidappsapk.co_1.apk" -o "C:/Users/farooq sharif/Desktop/mod/Green DOT Cash_androidappsapk.co_1"
I: Using Apktool 2.0.2 on Green DOT Cash_androidappsapk.co_1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\farooq sharif\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01010543
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResScalarValue.java:58)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:71)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Process exited with code 1

**Comment by Surendrajat** [comment]
Did you try decompiling with latest [apktool](https://ibotpeaches.github.io/Apktool/)?
