### ISSUE TITLE
Exception in thread "main" java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by hillz2** [vaibhavpandeyvpz/apkstudio#105]
I'm running Manjaro linux and I have tried to install apkstudio from AUR but I got this error 
```
==> Starting prepare()...
patch: **** Can't open patch file ../change-vendor-zip-warning.patch : No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
==> ERROR: Makepkg was unable to build apkstudio-git.
```
How do I install this app manually ? I have tried to clone your repo and use `./configure` but it didn't work.

**Comment by Surendrajat** [comment]
Hi. You don't need to install latest version of apkstudio as it's an appimage file. Just [download](https://github.com/vaibhavpandeyvpz/apkstudio/releases) and make it executable `chmod +x apkstudio-v4.0.3-linux_x86_64.AppImage`. It should be sufficient for any 64bit linux.
However, if you're running a 32bit linux or want to build apkstudio from source then please read this wiki on [building](https://github.com/vaibhavpandeyvpz/apkstudio/wiki/Building).

**Comment by hillz2** [comment]
I have successfully installed apkstudio but when I try to decompile an apk it throws this error: 
```
$ java -Xmx256m -jar /home/galih/.apkstudio/vendor/apktool.jar -f d /run/media/galih/Data/Dropbox/Public/myapp.apk -o /run/media/galih/Data/Dropbox/Public/myapp_mod
I: Using Apktool 2.3.1 on myapp.apk
I: Loading resource table...
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:375)
	at brut.androlib.res.decoder.StringBlock.decodeString(StringBlock.java:297)
	at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:110)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:126)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:341)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:257)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:233)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:599)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:73)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:65)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:72)
Process exited with code 1
```
Here's the app I want to decompile: https://www.dropbox.com/s/fas9ni28tpt9gzx/myapp.apk?dl=0
How do I decompile that apk ?

**Comment by Surendrajat** [comment]
Now this is `apktool` related issue. Seems like you are missing [some framework](https://ibotpeaches.github.io/Apktool/documentation/#framework-files). I see you've opened an issue there already. I hope it gets fixed after installing proper resource framework.

**Comment by webliqui** [comment]
Hi all,
I try to decompile an apk with the following command
`java -jar apktool_2.4.1.jar d -r -s --force-manifest -f`

but i get the erorr:

I: Copying raw resources...
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.base/java.nio.ByteBuffer.wrap(ByteBuffer.java:395)
	at brut.androlib.res.decoder.StringBlock.decodeString(StringBlock.java:297)
	at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:110)
	at brut.androlib.res.decoder.AXmlResourceParser.getName(AXmlResourceParser.java:176)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getName(XmlPullParserDelegate.java:57)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:64)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:142)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:154)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:162)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:204)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:134)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:113)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)


Maybe this app is protected with DexGuard.
Anyone can help me to understand this error.
Thank You!
