### ISSUE TITLE
Cannot build apk error occure during building

### ISSUE THREAD

**Issue by ppda1996** [vaibhavpandeyvpz/apkstudio#107]
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 25, --version-code, 11, --version-name, 2.0, -F, C:\Users\patel\AppData\Local\Temp\APKTOOL13915629971731382861.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\patel\apktool\framework\1.apk, -S, E:\New folder (2)\com.prem.smileindia\res, -M, E:\New folder (2)\com.prem.smileindia\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
	at brut.androlib.Androlib.buildResources(Androlib.java:403)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 25, --version-code, 11, --version-name, 2.0, -F, C:\Users\patel\AppData\Local\Temp\APKTOOL13915629971731382861.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\patel\apktool\framework\1.apk, -S, E:\New folder (2)\com.prem.smileindia\res, -M, E:\New folder (2)\com.prem.smileindia\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [aapt, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 25, --version-code, 11, --version-name, 2.0, -F, C:\Users\patel\AppData\Local\Temp\APKTOOL13915629971731382861.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\patel\apktool\framework\1.apk, -S, E:\New folder (2)\com.prem.smileindia\res, -M, E:\New folder (2)\com.prem.smileindia\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:93)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more
Caused by: java.io.IOException: Cannot run program "aapt": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at brut.util.OS.exec(OS.java:84)
	... 7 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 12 more
Process exited with code 1

**Comment by Surendrajat** [comment]
This is [`apktool`](https://github.com/iBotPeaches/Apktool) related error. Since logs are incomplete (few more lines at the beginning could do) I'm assuming you're using latest version of `apktool`.
You can delete `C:\Users\patel\apktool\framework\1.apk` and try building again. If that doesn't solve it, please open an issue [here](https://github.com/iBotPeaches/Apktool/issues).

**Comment by Surendrajat** [comment]
You can provide me the apk you're trying to rebuild or since it's an `apktool` related issue, I'd recommend you to open an issue here instead.. https://github.com/iBotPeaches/Apktool/issues

**Comment by ppda1996** [comment]
ok now I created .apk file but at the time of installation, package
installer says application not installed????

**Comment by Surendrajat** [comment]
Must a something wrong with signature of apk..
Check if the apk is properly signed before installing(click sign and see the logs) and remove original apk from phone if installed(signature will conflict).
