### ISSUE TITLE
error in building

### ISSUE THREAD

**Issue by Ajesh21** [vaibhavpandeyvpz/apkstudio#110]
$ java -Xmx256m -jar C:/Users/ELCOT/.apkstudio/vendor/apktool.jar -f b "F:/APPS/Star Music Tag Editor_com.music.star.startag_69_2.0__mod" -o "F:/APPS/Star Music Tag Editor_com.music.star.startag_69_2.0__mod.apk"
I: Using Apktool 2.2.2
I: Smaling smali folder into classes.dex...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [aapt, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 19, --version-code, 69, --version-name, 2.0, --no-version-vectors, -F, C:\Users\ELCOT\AppData\Local\Temp\APKTOOL728048318886438902.tmp, -0, arsc, -0, arsc, -I, C:\Users\ELCOT\AppData\Local\apktool\framework\1.apk, -S, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\res, -M, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [aapt, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 19, --version-code, 69, --version-name, 2.0, --no-version-vectors, -F, C:\Users\ELCOT\AppData\Local\Temp\APKTOOL728048318886438902.tmp, -0, arsc, -0, arsc, -I, C:\Users\ELCOT\AppData\Local\apktool\framework\1.apk, -S, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\res, -M, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [aapt, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 19, --version-code, 69, --version-name, 2.0, --no-version-vectors, -F, C:\Users\ELCOT\AppData\Local\Temp\APKTOOL728048318886438902.tmp, -0, arsc, -0, arsc, -I, C:\Users\ELCOT\AppData\Local\apktool\framework\1.apk, -S, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\res, -M, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
Caused by: java.io.IOException: Cannot run program "aapt": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 10 more
Process exited with code 1

$ java -Xmx3000m -jar C:/Users/ELCOT/.apkstudio/vendor/apktool.jar -f b "F:/APPS/Star Music Tag Editor_com.music.star.startag_69_2.0__mod" -o "F:/APPS/Star Music Tag Editor_com.music.star.startag_69_2.0__mod.apk"
I: Using Apktool 2.2.2
I: Smaling smali folder into classes.dex...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [aapt, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 19, --version-code, 69, --version-name, 2.0, --no-version-vectors, -F, C:\Users\ELCOT\AppData\Local\Temp\APKTOOL11241248254228579501.tmp, -0, arsc, -0, arsc, -I, C:\Users\ELCOT\AppData\Local\apktool\framework\1.apk, -S, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\res, -M, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [aapt, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 19, --version-code, 69, --version-name, 2.0, --no-version-vectors, -F, C:\Users\ELCOT\AppData\Local\Temp\APKTOOL11241248254228579501.tmp, -0, arsc, -0, arsc, -I, C:\Users\ELCOT\AppData\Local\apktool\framework\1.apk, -S, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\res, -M, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [aapt, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 19, --version-code, 69, --version-name, 2.0, --no-version-vectors, -F, C:\Users\ELCOT\AppData\Local\Temp\APKTOOL11241248254228579501.tmp, -0, arsc, -0, arsc, -I, C:\Users\ELCOT\AppData\Local\apktool\framework\1.apk, -S, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\res, -M, F:\APPS\Star Music Tag Editor_com.music.star.startag_69_2.0__mod\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
Caused by: java.io.IOException: Cannot run program "aapt": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 10 more
Process exited with code 1
**plz help me to solve this 

> [**problem****]
![2018-05-24](https://user-images.githubusercontent.com/39589376/40483584-25c937b0-5f76-11e8-9fb0-792e4841ec16.jpg)

**Comment by Surendrajat** [comment]
`apktool-2.2.2` is outdated. Grab an update from [here](https://github.com/iBotPeaches/Apktool/releases).
