### ISSUE TITLE
Errors while compiling apk

### ISSUE THREAD

**Issue by ManoharOfficial** [vaibhavpandeyvpz/apkstudio#120]
I decompiled the APK, changed the icon in hdpi, and when I tried to build the apk, this is the error I get
$ java -Xmx128m -jar C:/Users/Manu/.apkstudio/vendor/apktool.jar -f b "C:/Users/Manu/Desktop/com.azati.quit_a1a8b_2013-10-22 - Copy" -o "C:/Users/Manu/Desktop/com.azati.quit_a1a8b_2013-10-22 - Copy.apk"
I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, --forced-package-id, 127, --min-sdk-version, 7, --version-code, 18, --version-name, 2.8, -F, C:\Users\Manu\AppData\Local\Temp\APKTOOL13374686708092644817.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\Manu\apktool\framework\1.apk, -S, C:\Users\Manu\Desktop\com.azati.quit_a1a8b_2013-10-22 - Copy\res, -M, C:\Users\Manu\Desktop\com.azati.quit_a1a8b_2013-10-22 - Copy\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
	at brut.androlib.Androlib.buildResources(Androlib.java:403)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, --forced-package-id, 127, --min-sdk-version, 7, --version-code, 18, --version-name, 2.8, -F, C:\Users\Manu\AppData\Local\Temp\APKTOOL13374686708092644817.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\Manu\apktool\framework\1.apk, -S, C:\Users\Manu\Desktop\com.azati.quit_a1a8b_2013-10-22 - Copy\res, -M, C:\Users\Manu\Desktop\com.azati.quit_a1a8b_2013-10-22 - Copy\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [aapt, p, --forced-package-id, 127, --min-sdk-version, 7, --version-code, 18, --version-name, 2.8, -F, C:\Users\Manu\AppData\Local\Temp\APKTOOL13374686708092644817.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\Manu\apktool\framework\1.apk, -S, C:\Users\Manu\Desktop\com.azati.quit_a1a8b_2013-10-22 - Copy\res, -M, C:\Users\Manu\Desktop\com.azati.quit_a1a8b_2013-10-22 - Copy\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:93)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more
Caused by: java.io.IOException: Cannot run program "aapt": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at brut.util.OS.exec(OS.java:84)
	... 7 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 12 more
Process exited with code 1
![screenshot 3](https://user-images.githubusercontent.com/7362543/46359026-ec2b2280-c685-11e8-9227-b3a6df0204d6.png)

**Comment by Surendrajat** [comment]
Just use the latest apk studio from here: https://github.com/vaibhavpandeyvpz/apkstudio/releases/latest

**Comment by ManoharOfficial** [comment]
That worked wonderfully. Thank you :)
