### ISSUE TITLE
Rebuild error

### ISSUE THREAD

**Issue by JackLauu** [vaibhavpandeyvpz/apkstudio#36]
When I decode a APK, and do nothing, when I just rebuild and install, it get a Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION] error. I don't know why. I wan't to debug a APK.

**Comment by vaibhavpandeyvpz** [comment]
Look for the logcat output while you install the apk to device. Package manager might be able to give you more details on why operation failed.
Run: ```adb logcat -v threadtime``` in terminal.

**Comment by JackLauu** [comment]
Thank you vaibhavpandeyvpz for your reply. Do you decode any APK from google play? I use logcat and get the error:
system_process W/ActivityManager: No content provider found for permission revoke: file:///data/local/tmp/Square Quick No Crop Photo_apkpure.com.apk
01-08 14:20:31.009 318-335/system_process W/PackageParser: Exception reading /data/app/vmdl1866096127.tmp
                                                           java.lang.NullPointerException
                                                               at android.content.pm.PackageParser.collectCertificates(PackageParser.java:619)
                                                               at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:7378)
                                                               at com.android.server.pm.PackageManagerService.access$1600(PackageManagerService.java:160)
                                                               at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:5675)
                                                               at android.os.Handler.handleCallback(Handler.java:615)
                                                               at android.os.Handler.dispatchMessage(Handler.java:92)
                                                               at android.os.Looper.loop(Looper.java:137)
                                                               at android.os.HandlerThread.run(HandlerThread.java:60)
Can you help me?

**Comment by vaibhavpandeyvpz** [comment]
seems like maybe the manifest isn't encoded properly. [apktool](https://github.com/iBotPeaches/Apktool) problem most probably.

**Comment by JackLauu** [comment]
I use the key icon and try to sign it, but it failed and report a error: Process exited with code -1

**Comment by vaibhavpandeyvpz** [comment]
you need to have java's **keytool** in **PATH**.

**Comment by JackLauu** [comment]
The PATH is ok, I can run it from cmd, and I have signed my own apk by build singed release version in Android Studio. I want to debug APKs in apkstudio.

**Comment by kavehahangar** [comment]
hi
first, my English is weak(sorry)
anyway, i used apk studio and decompiled and builded one apk file Properly.
but i decompiled two Another apk files and changed more files and tried to builed, but apk studio cant dose it ana Says feiled builed,

this is the values of opration:

I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.jf.smali.smaliParser.simple_name(smaliParser.java:2419)
	at org.jf.smali.smaliParser.label(smaliParser.java:7077)
	at org.jf.smali.smaliParser.ordered_method_item(smaliParser.java:2001)
	at org.jf.smali.smaliParser.statements_and_directives(smaliParser.java:1738)
	at org.jf.smali.smaliParser.method(smaliParser.java:1537)
	at org.jf.smali.smaliParser.smali_file(smaliParser.java:615)
	at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:82)
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:70)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:378)
	at brut.androlib.Androlib.buildSources(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:288)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Process exited with code 1


please help me.

**Comment by vaibhavpandeyvpz** [comment]
Those apks need more **java heap** to be processed. I remember I made an option to increase that in the **Settings** dialog.

**Comment by kavehahangar** [comment]
Thank you very much.
The problem was resolved.

**Comment by Fennoune7** [comment]
hi i can't rebuild apk and keystore after edit apk

**Comment by thekingrenz23** [comment]
men how can you determine the proper java heap for a android application project?

**Comment by Shivakumar-Challa** [comment]
Hi Could you please help me how to solve this.
I am totally new to the programming.

Thank you.

I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.jf.smali.smaliParser.simple_name(smaliParser.java:2405)
	at org.jf.smali.smaliParser.member_name(smaliParser.java:3884)
	at org.jf.smali.smaliParser.method_reference(smaliParser.java:6875)
	at org.jf.smali.smaliParser.insn_format35c_method(smaliParser.java:13542)
	at org.jf.smali.smaliParser.instruction(smaliParser.java:10067)
	at org.jf.smali.smaliParser.ordered_method_item(smaliParser.java:2015)
	at org.jf.smali.smaliParser.statements_and_directives(smaliParser.java:1738)
	at org.jf.smali.smaliParser.method(smaliParser.java:1537)
	at org.jf.smali.smaliParser.smali_file(smaliParser.java:615)
	at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:82)
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:70)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:378)
	at brut.androlib.Androlib.buildSources(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:288)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Process exited with code 1

**Comment by langithitam** [comment]
Hy @vaibhavpandeyvpz,

I got error message "Process exited with code 1", i've tried to increase java heap in setting.
I've tried 256 to 1024, but not working.
Any suggestion?

**Comment by sureshraygor** [comment]
I got error when build project 



$ java -Xmx128m -jar "C:/Users/SAVLI INFOTECH/.apkstudio/vendor/apktool.jar" -f b "D:/memory/New folder/JioPOS Plus" -o "D:/memory/New folder/JioPOS Plus.apk"
I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Unknown Source)
	at java.lang.String.<init>(Unknown Source)
	at org.jf.smali.smaliFlexLexer.yytext(smaliFlexLexer.java:3330)
	at org.jf.smali.smaliFlexLexer.newToken(smaliFlexLexer.java:3111)
	at org.jf.smali.smaliFlexLexer.yylex(smaliFlexLexer.java:3566)
	at org.jf.smali.smaliFlexLexer.nextToken(smaliFlexLexer.java:3037)
	at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:143)
	at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137)
	at org.antlr.runtime.CommonTokenStream.consume(CommonTokenStream.java:68)
	at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:106)
	at org.jf.smali.smaliParser.insn_format3rc_method(smaliParser.java:13996)
	at org.jf.smali.smaliParser.instruction(smaliParser.java:10137)
	at org.jf.smali.smaliParser.ordered_method_item(smaliParser.java:2015)
	at org.jf.smali.smaliParser.statements_and_directives(smaliParser.java:1738)
	at org.jf.smali.smaliParser.method(smaliParser.java:1537)
	at org.jf.smali.smaliParser.smali_file(smaliParser.java:615)
	at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:82)
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:70)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:378)
	at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:322)
	at brut.androlib.Androlib.build(Androlib.java:289)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Process exited with code 1


Please help i need apk file argent for bypass root
![root](https://user-images.githubusercontent.com/16596499/29207488-f37dd4ea-7ea3-11e7-8838-dc0f294d45af.jpg)
