### ISSUE TITLE
https://github.com/vaibhavpandeyvpz/apkstudio/issues

### ISSUE THREAD

**Issue by pikac1987** [vaibhavpandeyvpz/apkstudio#38]
There is an error when apktool try to copy file with special characters, in this case quotes.
Here is the full log:

$ java -Xmx768m -jar C:/Users/Pc/.apkstudio/vendor/apktool.jar -f d C:/Users/Pc/APKfile.com.apk -o C:/Users/Pc/APKfile.com
I: Using Apktool 2.0.2 on APKfile.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Pc\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:158)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:157)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: Error copying file: assets
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:149)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: config.xml""
	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:61)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:197)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:77)
	... 5 more
Caused by: java.io.FileNotFoundException: C:\Users\Pc\Downloads\APKfile.com\assets\config.xml"" (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 8 more
Process exited with code 1

Is there any workaround, way to change that files name?
btw. jadx decompiles it without problems, it just replaces that quotes with underscore

**Comment by vaibhavpandeyvpz** [comment]
This is an **apktool** issue, please report it [here](https://github.com/iBotPeaches/Apktool/issues).
