### ISSUE TITLE
recompiling dont work for any of the apps.

### ISSUE THREAD

**Issue by giteshdev** [vaibhavpandeyvpz/apkstudio#47]
I tried to decompile. and recopile without trying to change anything in the files.
gives this below error 
`$ java -Xmx999m -jar C:/Users/Administrator/.apkstudio/vendor/apktool.jar -f b C:/Users/Administrator/Desktop/com.youthhr.phonto-1 -o C:/Users/Administrator/Desktop/com.youthhr.phonto-1.apk
I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_9105513400897027620.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 19, --version-code, 45, --version-name, 1.7.2, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL3344456135871787459.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\Administrator\apktool\framework\1.apk, -S, C:\Users\Administrator\Desktop\com.youthhr.phonto-1\res, -M, C:\Users\Administrator\Desktop\com.youthhr.phonto-1\AndroidManifest.xml]
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
    at brut.androlib.Androlib.buildResources(Androlib.java:403)
    at brut.androlib.Androlib.build(Androlib.java:291)
    at brut.androlib.Androlib.build(Androlib.java:261)
    at brut.apktool.Main.cmdBuild(Main.java:225)
    at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_9105513400897027620.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 19, --version-code, 45, --version-name, 1.7.2, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL3344456135871787459.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\Administrator\apktool\framework\1.apk, -S, C:\Users\Administrator\Desktop\com.youthhr.phonto-1\res, -M, C:\Users\Administrator\Desktop\com.youthhr.phonto-1\AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
    ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_9105513400897027620.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 19, --version-code, 45, --version-name, 1.7.2, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL3344456135871787459.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\Administrator\apktool\framework\1.apk, -S, C:\Users\Administrator\Desktop\com.youthhr.phonto-1\res, -M, C:\Users\Administrator\Desktop\com.youthhr.phonto-1\AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:93)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
    ... 6 more
Caused by: java.io.IOException: Cannot run program "C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_9105513400897027620.tmp": CreateProcess error=1450, Insufficient system resources exist to complete the requested service
    at java.lang.ProcessBuilder.start(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at brut.util.OS.exec(OS.java:84)
    ... 7 more
Caused by: java.io.IOException: CreateProcess error=1450, Insufficient system resources exist to complete the requested service
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(Unknown Source)
    at java.lang.ProcessImpl.start(Unknown Source)
    ... 11 more
Process exited with code 1
`

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
