### ISSUE TITLE
brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by FreeVicto** [vaibhavpandeyvpz/apkstudio#54]
$ java -Xmx512m -jar "C:/Documents and Settings/NW/.apkstudio/vendor/apktool.jar" -f d C:/SPB/yandex-com.spb.shell3d.apk -o C:/SPB/com.spb.shell3d
I: Using Apktool 2.1.0 on yandex-com.spb.shell3d.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Documents and Settings\NW\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values _/_ XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Process exited with code 0

$ java -Xmx512m -jar "C:/Documents and Settings/NW/.apkstudio/vendor/apktool.jar" -f b C:/SPB/com.spb.shell3d -o C:/SPB/com.spb.shell3d.apk
I: Using Apktool 2.1.0
I: Smaling smali folder into classes.dex...
I: Building resources...
W: warning: string 'date_year_toggle' has no default translation.
W: warning: string 'dialer_name' has no default translation.
W: warning: string 'dialog_shell_loading_first' has no default translation.
W: warning: string 'so_load_failed_reinstall' has no default translation.
W: warning: string 'so_load_failed_text' has no default translation.
W: warning: string 'so_load_failed_title' has no default translation.
W: C:\SPB\com.spb.shell3d\res\layout\logger_list_separator.xml:2: error: Error: Resource is not public. (at 'textColor' with value '@android:color/dim_foreground_dark').
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\DOCUME~1\NW\LOCALS~1\Temp\brut_util_Jar_661845726338048951.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 14, --version-code, 21536, --version-name, 1.6.4, -F, C:\DOCUME~1\NW\LOCALS~1\Temp\APKTOOL6152217143740282178.tmp, -0, arsc, -0, dat, -0, bin, -0, arsc, -I, C:\Documents and Settings\NW\apktool\framework\1.apk, -S, C:\SPB\com.spb.shell3d\res, -M, C:\SPB\com.spb.shell3d\AndroidManifest.xml]
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
    at brut.androlib.Androlib.buildResources(Androlib.java:371)
    at brut.androlib.Androlib.build(Androlib.java:281)
    at brut.androlib.Androlib.build(Androlib.java:254)
    at brut.apktool.Main.cmdBuild(Main.java:224)
    at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\DOCUME~1\NW\LOCALS~1\Temp\brut_util_Jar_661845726338048951.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 14, --version-code, 21536, --version-name, 1.6.4, -F, C:\DOCUME~1\NW\LOCALS~1\Temp\APKTOOL6152217143740282178.tmp, -0, arsc, -0, dat, -0, bin, -0, arsc, -I, C:\Documents and Settings\NW\apktool\framework\1.apk, -S, C:\SPB\com.spb.shell3d\res, -M, C:\SPB\com.spb.shell3d\AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
    ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\DOCUME~1\NW\LOCALS~1\Temp\brut_util_Jar_661845726338048951.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 14, --version-code, 21536, --version-name, 1.6.4, -F, C:\DOCUME~1\NW\LOCALS~1\Temp\APKTOOL6152217143740282178.tmp, -0, arsc, -0, dat, -0, bin, -0, arsc, -I, C:\Documents and Settings\NW\apktool\framework\1.apk, -S, C:\SPB\com.spb.shell3d\res, -M, C:\SPB\com.spb.shell3d\AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:95)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:427)
    ... 6 more
Process exited with code 1

**Comment by FreeVicto** [comment]
Please give some help......

**Comment by Xstar97** [comment]
what android apk are you trying to decompile/recompile?
I may be able to help as I never seen this error before

**Comment by VivekGadhvi** [comment]
@FreeVicto I would recommend you to to replace the apktool.jar with[ this](https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.1.0.jar) one.

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
