### ISSUE TITLE
Recompilation: Failed to build... open project.

### ISSUE THREAD

**Issue by 061833** [vaibhavpandeyvpz/apkstudio#57]
Hi there.

Just installed APK Studio and decompilled an app with aim to remove ads from it...

Everything worked well until Project was editied and recompilation of open project was launched... one time, two time, multiple time... it always says, that: **Failed to build.** **D:/DOCS/A-STUDIO/ALI APP/APK/Bla-bla... Please, check output.** Refer to screenshot: http://prntscr.com/bcief5

Interesting point that APK Studio **created Build and apk folders** but NOTHING inside.... Refer to screenshot: http://prntscr.com/bcifbk

Q: What's wrong with it OR what I do wrong with recompilation?
Q: Can you please help to solve this issue?

Thank you!

**Comment by mohroyhannahado** [comment]
I also had the same problem , is there who can help ?

**Comment by oerlex** [comment]
You should check the output in the console. I have the same issue and for me it throws the following exception when adding the android:debuggable="true" flag to the application tag in the app:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.jf.smali.smaliParser.simple_name(smaliParser.java:2408)
	at org.jf.smali.smaliParser.member_name(smaliParser.java:3884)
	at org.jf.smali.smaliParser.field_reference(smaliParser.java:6988)
	at org.jf.smali.smaliParser.insn_format22c_field(smaliParser.java:12050)
	at org.jf.smali.smaliParser.instruction(smaliParser.java:9857)
	at org.jf.smali.smaliParser.ordered_method_item(smaliParser.java:2015)
	at org.jf.smali.smaliParser.statements_and_directives(smaliParser.java:1738)
	at org.jf.smali.smaliParser.method(smaliParser.java:1537)
	at org.jf.smali.smaliParser.smali_file(smaliParser.java:615)
	at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:82)
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:70)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:378)
	at brut.androlib.Androlib.buildSources(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:288)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Process exited with code 1

Removing the debuggable flag again results in :+1: 

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.antlr.runtime.tree.BaseTree.createChildrenList(BaseTree.java:257)
	at org.antlr.runtime.tree.BaseTree.addChild(BaseTree.java:125)
	at org.antlr.runtime.tree.BaseTreeAdaptor.addChild(BaseTreeAdaptor.java:112)
	at org.jf.smali.smaliParser.insn_format12x(smaliParser.java:10725)
	at org.jf.smali.smaliParser.instruction(smaliParser.java:9661)
	at org.jf.smali.smaliParser.ordered_method_item(smaliParser.java:2015)
	at org.jf.smali.smaliParser.statements_and_directives(smaliParser.java:1738)
	at org.jf.smali.smaliParser.method(smaliParser.java:1537)
	at org.jf.smali.smaliParser.smali_file(smaliParser.java:615)
	at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:82)
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:70)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:378)
	at brut.androlib.Androlib.buildSources(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:288)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Process exited with code 1


Anyone with an idea ?

**Comment by Surendrajat** [comment]
Java Heap Size problem.
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
