### ISSUE TITLE
Apktool d49d3de after deleting framework\1.apk worked OK

### ISSUE THREAD

**Issue by limelect** [vaibhavpandeyvpz/apkstudio#72]
It seem i had OLD version of  C:\Users\LimElect\apktool\framework\1.apk
so Dicompiling had an error.
Then i deleted C:\Users\LimElect\apktool\framework
and things got OK.

$ java -Xmx128m -jar C:/Users/LimElect/.apkstudio/vendor/apktool.jar -f d C:/Android_Dicompile/com.livetv.android.apps.uktvnow.apk -o C:/Android_Dicompile/com.livetv.android.apps.uktvnow
I: Using Apktool 2.0.2 on com.livetv.android.apps.uktvnow.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\LimElect\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=interpolator, value=0x010c000d
W: Could not decode attr value, using undecoded value instead: ns=android, name=interpolator, value=0x010c000f
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01010462
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Process exited with code 1

$ java -Xmx128m -jar C:/Users/LimElect/.apkstudio/vendor/apktool.jar -f d C:/Android_Dicompile/com.livetv.android.apps.uktvnow.apk -o C:/Android_Dicompile/com.livetv.android.apps.uktvnow
I: Using Apktool 2.0.2 on com.livetv.android.apps.uktvnow.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\LimElect\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Process exited with code 0

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
