### ISSUE TITLE
APK decompiling error

### ISSUE THREAD

**Issue by MPeti1** [vaibhavpandeyvpz/apkstudio#74]
I wanted to decompile this apk: 
[miuisystem.apk.zip](https://github.com/vaibhavpandeyvpz/apkstudio/files/752848/miuisystem.apk.zip)

then i got this error:
`$ java -Xmx128m -jar C:/Users/masap/.apkstudio/vendor/apktool.jar -f d "C:/Users/masap/Documents/Android/Redmi 3S Prime/appműhely/miuisystem.apk/app/miuisystem.apk" -o "C:/Users/masap/Documents/Android/Redmi 3S Prime/appműhely/miuisystem.apk/app/miuisystem" -s
I: Using Apktool 2.0.2 on miuisystem.apk
I: Loading resource table...
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (android.miui), pkgId: 17
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\masap\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x100d0033
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x100d0017
I: Renamed manifest package found! Replacing com.miui.system with miui.system
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x10020005
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_v, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_first_v, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_v, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_middle_v, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_v, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=state_last_v, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=miui, name=name, value=0x00000008
Exception in thread "main" java.lang.NullPointerException
	at java.io.Writer.write(Unknown Source)
	at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
	at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:120)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:105)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Process exited with code 1
`

What is the problem?
The reason i wanted to decompile (and then edit and recompile) the app is because i want to make customizations to the system (MIUI 8 global Dev 7.1.19). I'm using Xposed framework and some apps that can customize the system, but I want to do more customization.

**Comment by Surendrajat** [comment]
It's because older version of Apktool.
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
