### ISSUE TITLE
Error while building Maps.apk after updating Android manifest to debuggable

### ISSUE THREAD

**Issue by Sonurehal** [vaibhavpandeyvpz/apkstudio#78]
$ java -Xmx128m -jar C:/Users/skumar/.apkstudio/vendor/apktool.jar -f b C:/sdk-tools-windows-3859397/platform-tools/Maps -o C:/sdk-tools-windows-3859397/platform-tools/Maps.apk
I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
at org.jf.smali.smaliParser.simple_name(smaliParser.java:2418)
at org.jf.smali.smaliParser.member_name(smaliParser.java:3884)
at org.jf.smali.smaliParser.method_reference(smaliParser.java:6875)
at org.jf.smali.smaliParser.insn_format35c_method(smaliParser.java:13542)
at org.jf.smali.smaliParser.instruction(smaliParser.java:10067)
at org.jf.smali.smaliParser.ordered_method_item(smaliParser.java:2015)
at org.jf.smali.smaliParser.statements_and_directives(smaliParser.java:1738)
at org.jf.smali.smaliParser.method(smaliParser.java:1537)
at org.jf.smali.smaliParser.smali_file(smaliParser.java:615)
at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:82)
at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:70)
at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:378)
at brut.androlib.Androlib.buildSources(Androlib.java:305)
at brut.androlib.Androlib.build(Androlib.java:288)
at brut.androlib.Androlib.build(Androlib.java:261)
at brut.apktool.Main.cmdBuild(Main.java:225)
at brut.apktool.Main.main(Main.java:84)
Process exited with code 1

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
