### ISSUE TITLE
[OSX] DirectoryException on APKs with spaces in the filename

### ISSUE THREAD

**Issue by willpharaoh** [vaibhavpandeyvpz/apkstudio#79]
Successfully compiled on OSX Yosemitie, but when you load an APK with spaces in the filenam, the apk is deleted and a java exception thrown. I redownloaded the apk and removed the spaces, and it worked.

`: Using Apktool 2.2.2 on Fire Emblem Heroes_v1.3.0_dbg.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.io.FileNotFoundException: /Users/me/apk/Fire Emblem Heroes_v1.3.0_dbg.apk (No such file or directory)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:272)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: java.io.FileNotFoundException: /Users/me/apk/Fire Emblem Heroes_v1.3.0_dbg.apk (No such file or directory)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:51)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:270)
	... 3 more
Caused by: java.io.FileNotFoundException: /Users/me/apk/Fire Emblem Heroes_v1.3.0_dbg.apk (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
Process exited with code 1
`

No spaces where present in any preceding directories in it's full path, but that should be validated as well.

**Comment by vaibhavpandeyvpz** [comment]
Noted for fix in next release.
