### ISSUE TITLE
Cant build project

### ISSUE THREAD

**Issue by sureshraygor** [vaibhavpandeyvpz/apkstudio#86]
I got error when build project

$ java -Xmx128m -jar "C:/Users/SAVLI INFOTECH/.apkstudio/vendor/apktool.jar" -f b "D:/memory/New folder/JioPOS Plus" -o "D:/memory/New folder/JioPOS Plus.apk"
I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOfRange(Unknown Source)
at java.lang.String.(Unknown Source)
at org.jf.smali.smaliFlexLexer.yytext(smaliFlexLexer.java:3330)
at org.jf.smali.smaliFlexLexer.newToken(smaliFlexLexer.java:3111)
at org.jf.smali.smaliFlexLexer.yylex(smaliFlexLexer.java:3566)
at org.jf.smali.smaliFlexLexer.nextToken(smaliFlexLexer.java:3037)
at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:143)
at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137)
at org.antlr.runtime.CommonTokenStream.consume(CommonTokenStream.java:68)
at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:106)
at org.jf.smali.smaliParser.insn_format3rc_method(smaliParser.java:13996)
at org.jf.smali.smaliParser.instruction(smaliParser.java:10137)
at org.jf.smali.smaliParser.ordered_method_item(smaliParser.java:2015)
at org.jf.smali.smaliParser.statements_and_directives(smaliParser.java:1738)
at org.jf.smali.smaliParser.method(smaliParser.java:1537)
at org.jf.smali.smaliParser.smali_file(smaliParser.java:615)
at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:82)
at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:70)
at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:378)
at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:322)
at brut.androlib.Androlib.build(Androlib.java:289)
at brut.androlib.Androlib.build(Androlib.java:261)
at brut.apktool.Main.cmdBuild(Main.java:225)
at brut.apktool.Main.main(Main.java:84)
Process exited with code 1

Please help i need apk file argent for bypass root
![root](https://user-images.githubusercontent.com/16596499/29208271-1035ede0-7ea7-11e7-95e5-80795197562d.jpg)

**Comment by VivekGadhvi** [comment]
Have a look at this : https://stackoverflow.com/questions/1565388/increase-heap-size-in-java

**Comment by Surendrajat** [comment]
Heap size increased to 256MB in latest version so probably the issue is resolved.
