### ISSUE TITLE
failed to build..shows----- brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by staticjava0001** [vaibhavpandeyvpz/apkstudio#92]
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\myid\AppData\Local\Temp\brut_util_Jar_7060265811152342046.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 22, --version-code, 19, --version-name, 1.0.1, --no-version-vectors, -F, C:\Users\myid\AppData\Local\Temp\APKTOOL2279997091352613959.tmp, -0, arsc, -I, C:\Users\myid\AppData\Local\Temp\1.apk, -S, C:\Users\myid\.apkstudio\vendor\base1\res, -M, C:\Users\myid\.apkstudio\vendor\base1\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\myid\AppData\Local\Temp\brut_util_Jar_7060265811152342046.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 22, --version-code, 19, --version-name, 1.0.1, --no-version-vectors, -F, C:\Users\myid\AppData\Local\Temp\APKTOOL2279997091352613959.tmp, -0, arsc, -I, C:\Users\myid\AppData\Local\Temp\1.apk, -S, C:\Users\myid\.apkstudio\vendor\base1\res, -M, C:\Users\myid\.apkstudio\vendor\base1\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\myid\AppData\Local\Temp\brut_util_Jar_7060265811152342046.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 22, --version-code, 19, --version-name, 1.0.1, --no-version-vectors, -F, C:\Users\myid\AppData\Local\Temp\APKTOOL2279997091352613959.tmp, -0, arsc, -I, C:\Users\myid\AppData\Local\Temp\1.apk, -S, C:\Users\myid\.apkstudio\vendor\base1\res, -M, C:\Users\myid\.apkstudio\vendor\base1\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
Process exited with code 1

**Comment by VivekGadhvi** [comment]
Run apkstudio as administrator. Might work sometimes.
