### ISSUE TITLE
Failed to decode .apk file (just this one)

### ISSUE THREAD

**Issue by KeanuQ** [vaibhavpandeyvpz/apkstudio#98]
I have already decompiled some apks successfully but with [this one](http://www.mediafire.com/file/sicugyf6x2rl1dt/com.supercell.clashroyale.apk) it failed to decode.

Console:

`$ java -Xmx128m -jar C:/Users/Admin/.apkstudio/vendor/apktool.jar -f d "C:/Users/Admin/Apk/com.supercell.clashroyale.apk" -o "C:/Users/Admin/Apk/com.supercell.clashroyale"
I: Using Apktool 2.0.2 on com.supercell.clashroyale.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Admin\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01010543
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResScalarValue.java:58)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:71)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Process exited with code 1
`
![grafik](https://user-images.githubusercontent.com/34660029/34123333-7659b1d6-e42f-11e7-8086-2aa95f45d06f.png)

I would be pleased about any help :)

**Comment by VivekGadhvi** [comment]
Looks like Framework error. @KeanuQ   reinstall the [framework-res.apk](https://basketbuild.com/filedl/devs?dev=aniruddhc&dl=aniruddhc/framework-res.apk) and try again.

**Comment by KeanuQ** [comment]
how to reinstall the framework-res.apk?
where can I install this apk?

**Comment by Surendrajat** [comment]
I think the issue is with older apktool. Download [latest apktool](https://ibotpeaches.github.io/Apktool/) and replace C:/Users/Admin/.apkstudio/vendor/apktool.jar with it.
